### ISSUE TITLE
Revisit Notifications

### ISSUE THREAD

**Issue by adamwolf** [beeminder/beedroid#30]
_From @adamwolf on October 26, 2017 1:49_

Android notifications have gone through a few revisions since the work in Beedroid.  Figure out how they should work now, and do it that way instead.

_Copied from original issue: beeminder/beedroid-hist#5_

**Comment by adamwolf** [comment]
We'll certainly want to add notification channels, one for timer and one for zeno alerts.

**Comment by adamwolf** [comment]
I think we should autodismiss non-derailed zenos that are past their deadline.

**Comment by bsoule** [comment]
and possibly the android app can't tell the difference between "this goal is about to derail" and "this goal is about to reach its end date"? and alerts about both in the same way?

[this is from a second-hand user report, but has definitely been a problem in the past in other places, so totally plausible it could happen here too]

**Comment by dreeves** [comment]
Side note: In some ways I like how it's all "OMG this goal is about to ENDDDD". I mean, it's a bug for it to falsely say it's about to derail, but beehaviorally economically it's really bad for a goal to end and quietly go out of sight out of mind. At the very least an ended goal should stick itself to the top of your gallery and be in your face until you decide to archive it or restart it.

In short, don't fix this in what at first blush may be the obvious way. Want to talk more about the behavioral economics of imminently ending goals because they are rarely ending intentionally.

**Comment by adamwolf** [comment]
Actually, how about we use this as a non-actionable issue collector.  Once things become issuable, let's make focussed issues.

**Comment by adamwolf** [comment]
Once we target Android O, we get notification channels, which means we can group zenos together and keep timers separate.  That's nifty!

**Comment by adamwolf** [comment]
I have created #79 and #80 for handling goals about to end and goals that have ended. There are no obvious actions from this that have not been done as of 2.10.7.
